# Generated by Django 4.2.5 on 2023-09-26 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cognome', models.CharField(max_length=255)),
                ('indirizzo', models.CharField(max_length=255)),
                ('contatto', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Nave',
            fields=[
                ('num_registro', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('dimensioni', models.CharField(max_length=255)),
                ('proprietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ships.persona')),
            ],
        ),
    ]
