# Generated by Django 4.2.5 on 2023-09-26 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ships', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documenti/')),
                ('nave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ships.nave')),
            ],
        ),
        migrations.CreateModel(
            name='Certificato',
            fields=[
                ('codice', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('data_scadenza', models.DateTimeField(blank=True)),
                ('scaduto', models.BooleanField()),
                ('nave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ships.nave')),
            ],
        ),
    ]
